Repository GNAutoRota/GNAutoRota, pull requests merged in 2025-02, with the labels that each got.

#15 (ISSUES #5) ConflitoMerge/main/implementacaoFluxoLogin
  .gitignore
  App.xaml.cs
  AppShell.xaml
  Auth/FireBaseAuthClientInjecao.cs
  Auth/FirebaseServices.cs
  Classes/FbTokenResponse.cs
  Classes/RequisicoesGoogleServico.cs
  Dashboard.xaml.cs
  GNAutoRota.csproj
  MauiProgram.cs
  Models/DashboardViewModel.cs
  Models/LoginViewModel.cs
  Platforms/Android/AndroidManifest.xml
  Platforms/Android/google-services.json
  ViewPrincipal/DashBoard.xaml
  ViewPrincipal/DashBoard.xaml.cs
  Views/LoginPage.xaml.cs
Labels: inovação

#21 (ISSUES #18) splash modificado
  GNAutoRota.csproj
  Resources/Splash/splash.svg
Labels: melhoria

#22 trocado icone do login temporariamente
  GNAutoRota.csproj
  Resources/Images/icon_log_temp.png
  Views/LoginPage.xaml
Labels: melhoria

#24 Melhoria/main/trocaIconeApp
  GNAutoRota.csproj
  Resources/AppIcon/appicon.svg
  Resources/AppIcon/appiconfg.svg
  Views/LoginPage.xaml
Labels: melhoria

#25 (ISSUES #23) Erro visualização senha - Realizada troca do icone de vi…
  Views/LoginPage.xaml.cs
Labels: correção

#26 (ISSUES #16) Feita novas validações de erros de login
  Classes/Constantes.cs
  Models/LoginViewModel.cs
Labels: correção

#27 adicionado arquivo necessário para integração do firebase em dispositivos IOS
  GNAutoRota.csproj
  Platforms/iOS/GoogleService-Info.plist
Labels: melhoria
